#!/bin/bash
#GIT
push()
{
	echo "@Nome do novo commit a ser feito:@";
	read -e nome;

	git add --all;
	git commit -m "$nome";
	git push origin master;
}
pull()
{ 
	echo "@Verificando se existem alterações não recolhidas..@";
	git pull origin master; 
}
timeline()
{
	git log --pretty=format:"%C(bold magenta)%ad %C(red)%d|| %C(white)%s %C(red)|| %C(blue)[%cn]" --decorate --date=relative;
}
new()
{
	if [ "$1" == "" ]; then
	
		echo "@Introduza um "git link" correto.@"
		
	else
	
		git init;
		git remote add origin $1;
		echo "O início do desastre" > README.md;
		git add --all;
		git commit -m "O início do desastre";
		git push -u origin master;
		
	fi
}
throwback()
{
	git checkout HEAD -f > /dev/null;
	
	if [ $? -ne 0 ]; then
	
		echo "@Ocorreu um erro (possivelmente um conflito).@";
		
	else
		
		if [ "$1" == "" ] || [ "$1" -le 1 ]; then
	
			git revert --no-commit HEAD~1..HEAD;
			echo "@As mudanças foram revertidas para 1 commit atrás do commit mais atualizado.@";
		
		else
	
			git revert --no-commit HEAD~$1..HEAD;
			echo "@As mudanças foram revertidas para $1 commits atrás do commit mais atualizado.@";
		
		fi
		
	fi
}
current()
{ 
	git checkout HEAD -f > /dev/null; 
	
	if [ $? -eq 0 ]; then
	
		echo "@Foi regressado ao commit mais recente.@";
		
	else
	
		echo "@Ocorreu um erro (possivelmente um conflito).@";
		
	fi
}
status()
{ git status; }
diff()
{ echo "@Diferenças entre os dois commits:@"; git diff; }
help()
{
	echo "@@ DESCRIÇÃO DOS ALIAS/FUNÇÕES DO SGIT @@";
	echo "sgit push		» coloca as alterações locais no repositório";
	echo "sgit pull		» recolhe alterações ao repositório";
	echo "sgit timeline		» mostra a cronologia dos commits";
	echo "sgit new		» inicializa o repositório";
	echo "sgit status		» mostra o estado do commit";
	echo "sgit diff		» compara o commit local com o commit remoto";
	echo "sgit current		» volta para o commit atual";
	echo "sgit throwback		» volta atrás n commits";
	echo "@@ BOA SORTE! @@";
}

case $1 in

	push) push
	;;

	pull) pull
	;;
	
	new) new $2
	;;
	
	help) help
	;;	

	throwback) throwback $2
	;;

	current) current
	;;	

	status) status
	;;
	
	diff) diff
	;;
	
	timeline) timeline
	;;

	*) echo "@Opção não existente.@"; help
	;;

esac
